// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        Amap: typeof import('G:/work/My-Vue-App/src/views/demo/Amap.vue')['default']
        App: typeof import('G:/work/My-Vue-App/src/App.vue')['default']
        Flow: typeof import('G:/work/My-Vue-App/src/views/demo/Flow.vue')['default']
        FlowEchart: typeof import('G:/work/My-Vue-App/src/views/demo/FlowEchart.vue')['default']
        HelloWorld: typeof import('G:/work/My-Vue-App/src/views/HelloWorld.vue')['default']
    }
}

export {}
