// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        Amap: typeof import('/@/views/demo/Amap.vue')['default']
        Flow: typeof import('/@/views/demo/Flow.vue')['default']
        FlowEchart: typeof import('/@/views/demo/FlowEchart.vue')['default']
        HelloWorld: typeof import('/@/views/HelloWorld.vue')['default']
    }
}

// eslint-disable-next-line
export { }
