// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        App: typeof import('D:/work/My-Vue-App/src/App.vue')['default']
        HelloWorld: typeof import('D:/work/My-Vue-App/src/views/HelloWorld.vue')['default']
    }
}

export {}
